### ISSUE TITLE
Paste adds extra line break when copying from text box

### ISSUE THREAD

**Issue by o-l-e** [jbentzen/sketch-fast-text-transfer#2] opened 2020-08-18 19:13 UTC
Hi, i really find this plugin useful. Thanks for developing this.

I have experienced a bug for a long while:
1. i select a text box with one line of text
2. copy using "Fast Copy Text"
3. select another box (or more)
4. paste using "Fast Paste Text"

What happens is that it always adds an extra line break, causing the box expand vertically (obviously with the line break).
It would be really nice with a fix for this.

Thanks again for a really nice plugin!

<img width="969" alt="Screenshot 2020-08-18 at 21 12 08" src="https://user-images.githubusercontent.com/881495/90555348-840d5900-e197-11ea-9724-8b6961079750.png">

**Comment by jbentzen** [comment] 2020-08-19 05:14
Hi,

Happy to hear you enjoy this plugin. I was not able to reproduce the issue you experience using the latest version of Sketch (68). Would you mind telling me your system specs, macOS version, Sketch version and which plugins you have installed next to Fast Text Transfer? It could be some other clipboard altering service/software/plugin interfering.

**Comment by o-l-e** [comment] 2020-08-22 22:00
Hi there.

To be honest i didn't manage to reproduce this bug myself at the moment. Strange.
I am running the latest version of Sketch (68) on the latest version of OSX Catalina (10.15.6).
Sorry for posting this without testing, and i will post if it happens again.

Thanks for your reply.

**Comment by jbentzen** [comment] 2020-08-23 09:05
Hi,

No problem. Good to hear that it works. I will close this issue again. Just open another one should the issue resurface.

**Closed as completed by jbentzen** 2020-08-23 09:05 UTC
